const menu = [
    // {
    //     id: 1,
    //     title: 'buttermilk pancakes',
    //     category: 'Sweets',
    //     price: 15.99,
    //     img: './images/item-1.jpeg',
    //     desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    // },
    {
        id: 1,
        title: 'Greek Pizza',
        category: 'Pizza',
        price: "19.99$",
        img: "/images/item-1.jpeg",
        desc: `A light and flavorful pizza featuring feta, tomatoes, and spinach. I like to use a homemade whole wheat crust, rolled thin.`,
    },
    {
        id: 2,
        title: 'True Cheeseburger Pizza',
        category: 'Pizza',
        price: "21.99$",
        img: '/images/item-2.jpeg',
        desc: `This is a unique twist on two favorites: pizza and cheeseburgers! It is super fast to make, and you can easily add your favorite burger toppings such as lettuce and tomato. This is a family favorite and disappears fast!`,
    },
    {
        id: 3,
        title: 'BBQ Chicken Pizza',
        category: 'Pizza',
        price: "23.99$",
        img: '/images/item-3.jpeg',
        desc: `A topping of spicy barbeque sauce, diced chicken, cilantro, peppers, and onion all covered with cheese, and baked to bubbly goodness! `,
    },
    {
        id: 4,
        title: 'Pepperoni Pizza',
        category: 'Pizza',
        price: "19.99$",
        img: '/images/item-4.jpeg',
        desc: `This is something great to make ahead of time and then eat as leftovers later on. It's great hot or cold, just like pizza! I find that if you make 6 square slices, each slice is usually more than enough to fill you up. Feel free to add whatever toppings you normally eat on pizza. It will taste just as good!`,
    },
    {
        id: 5,
        title: 'White Pizza',
        category: 'Pizza',
        price: "17.99$",
        img: '/images/item-5.jpeg',
        desc: `Sausage and Alfredo pizza. So good you won't believe just how easy it is to make! It's kind of messy to eat, but totally worth it.`,
    },
    {
        id: 6,
        title: 'Jalapeno Pizza',
        category: 'Pizza',
        price: "19.99$",
        img: '/images/item-6.jpeg',
        desc: `All the goodness of jalapeno in a pizza topping.`,
    },
    {
        id: 7,
        title: 'Double Cheeseburgers',
        category: 'burger',
        price: "11.99$",
        img: '/images/item-7.jpeg',
        desc: `Roy Choi’s burgers look like the American classic, but get an Asian twist with toasted sesame seeds in the mayo and fresh shiso leaves on top of the lettuce.`,
    },
    {
        id: 8,
        title: 'Cheddar-and-Onion Smashed Burgers',
        category: 'burger',
        price: "12.99$",
        img: '/images/item-8.jpeg',
        desc: `The secret of this burger is the "Umami dust", a combination of bonito (dried tuna) flakes, seaweed and shiitake mushrooms with a pronounced savory Asian flavor.`,
    },
    {
        id: 9,
        title: 'Classic cheese-burger with fried potatoes',
        category: 'burger',
        price: "9.99$",
        img: '/images/item-9.jpeg',
        desc: `Simple, and tasty `,
    },
    {
        id: 10,
        title: 'Barbecue-Glazed Turkey Burgers',
        category: 'burger',
        price: "11.99$",
        img: '/images/item-10.jpeg',
        desc: `Turkey burgers are a popular lunch at our restaurant`,
    },
    {
        id: 11,
        title: 'corn salad',
        category: 'salads',
        price: "5.99$",
        img: '/images/item-11.jpg',
        desc: `Contains corn, feta cheese, onion, and basil. Suitable for diet`,
    },
    {
        id: 12,
        title: 'beet salad',
        category: 'salads',
        price: "5.99$",
        img: '/images/item-12.jpg',
        desc: `Open your appetite with this awesome, reddish salad.`,
    },
    {
        id: 13,
        title: 'tahini',
        category: 'salads',
        price: "5.99$",
        img: '/images/item-14.jpg',
        desc: `Everyone love it! Awesome with meats and fish`,
    },
    {
        id: 14,
        title: 'papa ghanoug',
        category: 'salads',
        price: "5.99$",
        img: '/images/item-13.jpg',
        desc: `The best choice with fish.`,
    },
    {
        id: 15,
        title: 'coleslaw',
        category: 'salads',
        price: "5.99$",
        img: '/images/item-15.jpg',
        desc: `ِContains cabbage, carrot, and mayo.`,
    },
    {
        id: 16,
        title: 'oreo dream',
        category: 'shakes',
        price: "8.99$",
        img: '/images/item-16.jpeg',
        desc: `Creamy oreo with chocolate icecream`,
    },
    {
        id: 17,
        title: 'pina colada',
        category: 'shakes',
        price: "8.99$",
        img: '/images/item-17.jpeg',
        desc: `Mix of pinapple chunks, coconut, and frozen vanilla icecream`,
    },
    {
        id: 18,
        title: 'chocolate-banana',
        category: 'shakes',
        price: "7.99$",
        img: '/images/item-18.jpeg',
        desc: `A delicious mix between chocolate and banana.`,
    },
    {
        id: 19,
        title: 'Chocolate–Peanut Butter',
        category: 'shakes',
        price: "9.99$",
        img: '/images/item-19.jpeg',
        desc: `Tasty blend of chocolate icecream and peanut butter`,
    },
    {
        id: 20,
        title: 'Chocolate–Peanut Butter',
        category: 'shakes',
        price: "9.99$",
        img: '/images/item-20.jpeg',
        desc: `Black rasberry icecream with some rasberries`,
    },
    {
        id: 21,
        title: 'Molten chocolate cake',
        category: 'sweets',
        price: "11.99$",
        img: '/images/item-21.jpeg',
        desc: `Molten chocolate cakes became famous for a reason: they're cakey on the outside with an irresistible center of warm dark chocolate flowing through the middle.`,
    },
    {
        id: 22,
        title: 'Crème Brûlée',
        category: 'sweets',
        price: "11.99$",
        img: '/images/item-22.jpg',
        desc: `Creamy custard with a caramelized topping, this Crème Brûlée is a classic French dessert that looks fancy!`,
    },
    {
        id: 23,
        title: 'Pancake with maple syrup',
        category: 'sweets',
        price: "8.99$",
        img: '/images/item-23.jpg',
        desc: `The best way to start your day`,
    },
    {
        id: 24,
        title: 'Waffle',
        category: 'seets',
        price: "9.99$",
        img: '/images/item-24.jpeg',
        desc: `A lovely, crispy waffle perfect for the morning.`,
    },
    {
        id: 25,
        title: 'Muffin',
        category: 'sweets',
        price: "9.99$",
        img: '/images/item-25.jpeg',
        desc: `Lite but awesome.`,
    },
];
export default menu;